name: Gradle Publish

on:
  release:
    types: [created]
    branches: [master,main]

jobs:
  build:
    uses: ./.github/workflows/gradle-build-template.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # include all history and tags
        
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
