name: Java Gradle Build Template

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version:
          - "8"
          - "11"
          - "17"

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{matrix.jdk_version}}
      uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.jdk_version}
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-report-${{matrix.jdk_version}}
        path: build/reports/
        retention-days: 1
