name: GitHub actions showcase

on: 
  workflow_dispatch:
    inputs:
      environment_name:
        description: environment name
        required: true

jobs:
  explore_github_actions:
    runs-on: ubuntu-latest
    
    outputs:
      docker_version: ${{steps.soft_versions.outputs.installed_docker_version}}
    
    steps:
      - run: echo "Username is ${{github.actor}}"
      
      - name: Display runner os
        run: echo "Runner os is ${{runner.os}}"
      
      - run: echo "Repository is ${{ github.repository }} and branch is ${{ github.ref }}"
      
      - run: echo "Event ${{github.event_name}} triggered the workflow"
      
      - name: Runner comes with preinstalled software
        id: soft_versions
        run: |
          echo "Display software versions"
          git -v
          docker -v
          node -v
          java -version
          echo "installed_docker_version=$(docker -v)" >> $GITHUB_OUTPUT
          
      - name: List files in the repository pre checkout
        run: ls ${{ github.workspace }}
        
      - uses: actions/checkout@v3
      
      - name: List files in the repository after checkout
        run: ls ${{ github.workspace }}

  display_info:
    runs-on: ubuntu-latest
    
    needs: explore_github_actions
    
    steps:
      - name: display requred job output
        env:
          GIVEN_DOCKER_VER: ${{needs.explore_github_actions.outputs.docker_version}}
        run: echo "given docker is $GIVEN_DOCKER_VER"
    
      - run: echo "${{github.event.inputs.environment_name}}"     
      
      - name: output workflow execution summary
        run: |
          echo "var | value" >> $GITHUB_STEP_SUMMARY
          echo "--- | ---" >> $GITHUB_STEP_SUMMARY
          echo "run id | $GITHUB_RUN_ID" >> $GITHUB_STEP_SUMMARY
          echo "actor | $GITHUB_ACTOR" >> $GITHUB_STEP_SUMMARY
          echo "repository|$GITHUB_REPOSITORY" >> $GITHUB_STEP_SUMMARY
          echo "branch|$GITHUB_REF" >> $GITHUB_STEP_SUMMARY
          echo "os|$RUNNER_OS" >> $GITHUB_STEP_SUMMARY
          
      
